version: "3"
services:
    mosquitto:
        container_name: mosquitto-mqtt
        image: eclipse-mosquitto
        restart: unless-stopped
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./Mosquitto/config:/mosquitto/config
            - ./Mosquitto/data:/mosquitto/data
            - ./Mosquitto/log:/mosquitto/log
    db:
        container_name: postgres-db
        image: postgres
        restart: unless-stopped
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          # - PGDATA=/var/lib/postgresql/data/db-files/
        ports:
          - '5432:5432'
        volumes:
          - ./postgres/data:/var/lib/postgresql/data/
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Etc/UTC
          - VERSION=docker
          - PLEX_CLAIM= #optional
        volumes:
          - ./media/library:/config
          - ./media/tvseries:/tv
          - ./media/movies:/movies
        restart: unless-stopped
    transmission-openvpn:
        container_name: transmission-vpn
        cap_add:
            - NET_ADMIN
        restart: unless-stopped
        volumes:
            - ./transmission/data:/data
            - ./transmission/config:/config
            - ./transmission/cyberghost:/etc/openvpn/custom/
            - ./transmission/downloads:/downloads
        environment:
            - OPENVPN_PROVIDER=CUSTOM
            - OPENVPN_CONFIG=openvpn
            - OPENVPN_USERNAME=5Nxvdxh4Cs
            - OPENVPN_PASSWORD=fEb37txmgk
            - LOCAL_NETWORK=192.168.0.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ./sonarr/config:/config
            - ./media/tvseries:/tv #optional
            - ./transmission/data/completed:/downloads #optional
            - ./media:/mnt/media
        ports:
            - 8989:8989
        restart: unless-stopped
